# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

---
release_tags: &release_tags
  tags:
    only: /^v\d+(\.\d+){2}(-.*)?$/


docker_config: &docker_config
  docker:
    - image: circleci/node:11-browsers

version: 2.0
workflows:
  version: 2
  build:
    jobs:
      - test:
          filters: *release_tags
      - publish_npm:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            <<: *release_tags

jobs:
  test:
    <<: *docker_config
    steps:
      - checkout
      - run:
          name: Install modules and dependencies.
          command: npm install
      - run:
          name: Run unit tests.
          command: npm run test
      - run:
          name: Submit coverage data to codecov.
          command: npm run codecov
          when: always
  publish_npm:
    <<: *docker_config
    steps:
      - checkout
      - run:
          name: Install modules and dependencies.
          command: npm install
      # Run publish script for each package suffix and its NPM wombat token.
      - run: .circleci/publish.sh initial-load $WOMBAT_TOKEN_INITIAL_LOAD
      - run: .circleci/publish.sh core $WOMBAT_TOKEN_CORE
      - run: .circleci/publish.sh exporter-ocagent $WOMBAT_TOKEN_EXPORTER_OCAGENT
      - run: .circleci/publish.sh instrumentation-perf $WOMBAT_TOKEN_INSTRUMENTATION_PERF
      - run: .circleci/publish.sh propagation-tracecontext "$WOMBAT_TOKEN_PROPAGATION_TRACECONTEXT"
      - run: .circleci/publish.sh scripts "$WOMBAT_TOKEN_SCRIPTS"      
      - run: .circleci/publish.sh types "$WOMBAT_TOKEN_TYPES"
      - run: .circleci/publish.sh instrumentation-zone $WOMBAT_TOKEN_INSTRUMENTATION_ZONE
      - run: .circleci/publish.sh instrumentation-zone-peer-dep $WOMBAT_TOKEN_INSTRUMENTATION_ZONE_PEER_DEP
